version: '3.9'

services:
  spring-boot-app:
    build: .
    image: youlhee/trendly:redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_PORT: ${SPRING_PORT}  # 서버 포트 지정

      # Datasource 설정 (application-dev.yml에서 ${server.base-url}을 참조함)
      PUBLIC_NAME: ${PUBLIC_NAME}
      PUBLIC_PASSWORD: ${PUBLIC_PASSWORD}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}

      # RabbitMQ
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

    networks:
      - trendly-network


  mysql-db:
    image: mysql:8.0.33
    container_name: trendly-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - trendly-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - trendly-network
    restart: always
    command: redis-server --port 6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - trendly-network

volumes:
  db_data:
  redis-data:
  rabbitmq_data:

networks:
  trendly-network:
    external: true