pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'org.springframework.boot' version '3.4.2'
        id 'io.spring.dependency-management' version '1.1.7'
    }
}

rootProject.name = 'trendly'
include 'common'
include 'user'
include 'discussion'
include 'trending'
include 'websocket'
include 'batch'
include 'trendly'

