
# 서버 설정
server:
  port: ${SPRING_PORT:8080}  # ??????? ??? ?? ?? ??
  error:
    whitelabel:
      enabled: false  # Spring Boot ?? ?? ???(whitelabel error page) ????
  base-url: localhost
  url: http://localhost:8080
# ??? ?????? ??
spring:
  batch:
    job:
      enabled: false

  application:
    name: trendly  # 애플리케이션 이름 설정
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher    # 원본 값 사용
  datasource:
    url: jdbc:mysql://${server.base-url}:3306/trendly?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true  # MySQL ?????? ?? URL
    username: ${PUBLIC_NAME:trendly}
    password: ${PUBLIC_PASSWORD:rootroot}
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ???
    hikari:  # HikariCP(??? ?) ??
      pool-name: HikariCP  # ??? ? ??
      maximum-pool-size: 10  # ?? ??? ? ??
      minimum-idle: 5  # ?? ?? ??? ??
      idle-timeout: 30000  # ??? ?? ?? ?? ??(ms)
      connection-timeout: 20000  # ??? ?? ?? ??(ms)
      max-lifetime: 1800000  # ??? ?? ??(ms)
      connection-test-query: SELECT 1  # ??? ??? ?? ??

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create  # 데이터베이스 스키마를 업데이트로 설정
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL에 맞는 Hibernate 방언 설정
    show-sql: true  # SQL 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true  # SQL ?? ?? ??(???? ??)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0ff4f0cc878339e75d6a7f55b88fa027
            redirect-uri: http://${server.base-url}:8080/auth/kakao/callback
    #  # MongoDB ??
    #  data:
    #    mongodb:
    #      uri: mongodb://localhost:27017/adarticle-db  # MongoDB 연결 URI

    # Redis ??
  redis:
    host: 54.180.63.180  # Redis ???
    port: ${REDIS_PORT:6379}  # Redis ?? ??

# RabbitMQ ??
rabbitmq:
  host: localhost  # .env?? ????? ???
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_DEFAULT_USER}
  password: ${PUBLIC_PASSWORD}  # .env? ???? ?? ??

jwt:
  secret: testSecretKey20230327testSecretKey20230327testSecretKey20230327
  access-token:
    expiration: 300000                       # 3m
  refresh-token:
    expiration: 300000