
# ?? ??
server:
  port: ${SPRING_PORT}  # ??????? ??? ?? ?? ??
  error:
    whitelabel:
      enabled: false  # Spring Boot ?? ?? ???(whitelabel error page) ????

# ??? ?????? ??
spring:
  profiles:
    active: dev  # ???? ????
  batch:
    job:
      enabled: false

  application:
    name: trendly  # ?????? ?? ??

  # ?????? ??
  datasource:
    url: jdbc:mysql://localhost:3306/trendly-db  # MySQL ?????? ?? URL
    username: ${PUBLIC_NAME}  # ?????? ??? ??
    password: ${PUBLIC_PASSWORD}   # ?????? ????
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ???
    hikari:  # HikariCP(??? ?) ??
      pool-name: HikariCP  # ??? ? ??
      maximum-pool-size: 10  # ?? ??? ? ??
      minimum-idle: 5  # ?? ?? ??? ??
      idle-timeout: 30000  # ??? ?? ?? ?? ??(ms)
      connection-timeout: 20000  # ??? ?? ?? ??(ms)
      max-lifetime: 1800000  # ??? ?? ??(ms)
      connection-test-query: SELECT 1  # ??? ??? ?? ??

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create  # ?????? ???? ????? ??
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL? ?? Hibernate ?? ??
    show-sql: true  # SQL ?? ?? ???
    properties:
      hibernate:
        format_sql: true  # SQL ?? ?? ??(???? ??)
#
#  # MongoDB ??
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/adarticle-db  # MongoDB ?? URI

    # Redis ??
    redis:
      host: localhost  # Redis ???
      port: ${REDIS_PORT}  # Redis ?? ??

  # RabbitMQ ??
  rabbitmq:
    host: localhost  # .env?? ????? ???
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${PUBLIC_PASSWORD}  # .env? ???? ?? ??